name: üçé macOS Builds
on:
  workflow_call:

jobs:
  macos:
    runs-on: "macos-latest"
    name: macOS Build ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: [universal]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
    
      - name: Build ${{ matrix.arch }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: macos
      
      - name: Sign frameworks Debug
        shell: pwsh
        env:
          APPLE_CERT_BASE64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          APPLE_CERT_PASSWORD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          APPLE_DEV_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          APPLE_DEV_PASSWORD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          APPLE_DEV_APP_ID: ${{ secrets.PROD_MACOS_APPLE_DEV_APP_ID }}
        run: ./scripts/ci-sign-macos.ps1 dist/addons/godot-box2d/bin/libgodot-box2d.macos.template_debug.framework
        if: ${{ env.APPLE_DEV_ID }}
      
      - name: Sign frameworks Release
        shell: pwsh
        env:
          APPLE_CERT_BASE64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          APPLE_CERT_PASSWORD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          APPLE_DEV_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          APPLE_DEV_PASSWORD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          APPLE_DEV_APP_ID: ${{ secrets.PROD_MACOS_APPLE_DEV_APP_ID }}
        run: ./scripts/ci-sign-macos.ps1 dist/addons/godot-box2d/bin/libgodot-box2d.macos.template_release.framework
        if: ${{ env.APPLE_DEV_ID }}

      - name: Upload ${{ matrix.arch }}
        uses: ./.github/actions/upload
